### ISSUE TITLE
Beat Saber logo then black screen

### ISSUE THREAD

**Issue by Adblue** [NyanBlade/BeatSaberQuestInstaller#24]
Hey there friendly folks. I have been using this lovely program for about a week and it has been awesome. Upon adding some new songs, everything just stopped working. beat saber logo, then DARKNESS. NOTHING BUT THE VOID. I've done uninstalls, reinstalls, a factory reset, tried just using one song that I KNOW worked before. Nothing fixes it. On top of this, the only way to uninstall beat saber after this happens, is through the Mod Installer as the quest library page will not work. This is a truly baffling event. I just want my custom jams to work again.

**Comment by DoowronDog** [comment]
Not sure why but Most likely an incompatible song or two(even though they worked in the past). This happened to me as well and I removed the last few songs I had added and it worked again. To avoid it from happening again I try to add only a few tracks at a time like you did. Really no concrete solution I’ve been able to find and it’s been trial and error for me.

**Comment by rafikiki** [comment]
How did you wind up uninstalling it? You mentioned via the Mod Installer but I'm not sure what that's referring to. Looks like a new version of beat saber dropped today which is causing the problems. 

e: wound up manually uninstalling it with adb:
adb uninstall com.beatgames.beatsaber

**Comment by DoowronDog** [comment]
I used ESFile Explorer to uninstall directly from the Quest. Otherwise ADB uninstall works too.

**Comment by barodactyl** [comment]
Any known good songs that work here? I have been unsuccessful on quest all night. Same issue as everyone else... get blackscreen on launch??

Logcat logs aren't helpful

**Comment by jacobnuttall** [comment]
It's because of the Beat Saber update to 1.0.1.

**Comment by SoonerDoc** [comment]
Having exact same issue as adblue since Sunday.

**Comment by link2231** [comment]
a base uninstall that worked for me was the file undoit.bat in dist. it also reinstalls it but doesnt keep custom songs.

**Comment by robbmh87** [comment]
Awesome thanks. Ill look for it. Do you think the ability to add custom songs will come back? Or just wait for the official release of it?

**Comment by link2231** [comment]
> Awesome thanks. Ill look for it. Do you think the ability to add custom songs will come back? Or just wait for the official release of it? From: link2231 <notifications@github.com> Sent: Wednesday, June 5, 2019 4:19 AM To: NyanBlade/BeatSaberQuestInstaller <BeatSaberQuestInstaller@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [NyanBlade/BeatSaberQuestInstaller] Beat Saber logo then black screen (#24) Attention: This email came from an external source. Do not open attachments or click on links from unknown senders or unexpected emails. a base uninstall that worked for me was the file undoit.bat in dist. it also reinstalls it but doesnt keep custom songs. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/3EUBEw7LxK1Wxi8B53wQn6F7Vc?u=https%3A%2F%2Fgithub.com%2FNyanBlade%2FBeatSaberQuestInstaller%2Fissues%2F24%3Femail_source%3Dnotifications%26email_token%3DAMIEHTPZ4YGMCJFPTAU57ILPY6HKRA5CNFSM4HTABQOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW7IREY%23issuecomment-499026067>, or mute the thread<https://clicktime.symantec.com/3Tz2YcvYV3nHnq6BWYjUK327Vc?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMIEHTPV75JNWP5YOJ3LQZTPY6HKRANCNFSM4HTABQOA>.
> […](#)
> ------------------------------------------------------------------- The information transmitted by this e-mail and any included attachments are from ARUP Laboratories and are intended only for the recipient. The information contained in this message is confidential and may constitute inside or non-public information under international, federal, or state securities laws, or protected health information and is intended only for the use of the recipient. Unauthorized forwarding, printing, copying, distributing, or use of such information is strictly prohibited and may be unlawful. If you are not the intended recipient, please promptly delete this e-mail and notify the sender of the delivery error or you may call ARUP Laboratories Compliance Hot Line in Salt Lake City, Utah USA at (+1 (800) 522-2787 ext. 2100

after i uninstalled it i tried adding different songs slowly and it worked for me, so give it a try and see what you can do. took an afternoon of tinkering for me to figure out how to fix it

**Comment by NyanBlade** [comment]
Black screen issue should be mostly fixed in 0.6 (except from broken songs)
https://github.com/NyanBlade/BeatSaberQuestInstaller/releases

Open a new issue if the problem still persists
