### ISSUE TITLE
Not Working For Me

### ISSUE THREAD

**Issue by SoonerDoc** [NyanBlade/BeatSaberQuestInstaller#25]
No matter what I try, can't get this to work.

Tried v0.4.  Tried v0.5.  Tried two different PCs.  Tried 1 song.  Tried 10.

Whenever I run the installer in step 6, it seems like something goes wrong.  I go into my quest and beat saber is not there any longer.  Redownload beat saber in the quest.  Connect everything back and run step 6 again.  This time it looks like it works.  Get into quest and start beat saber.  See the beats saber logo in red and blue and then just a dark, blank screen no matter what (close app, reboot, whatever).  Whenever i start the app logo then blank screen.  

Can't delete the app and have to factory reset the quest.  Done this 3 times.  Same thing every time. 

I am stuck.  I'm sure I am doing something stupid.  I just dont know what it is.

Thanks in advance.

**Comment by rafikiki** [comment]
new beat saber version came out a couple of hours ago, unfortunately it breaks mods until the modding software is updated.

**Comment by SoonerDoc** [comment]
Don’t think it is that. Been trying for last couple of days.

**Comment by link2231** [comment]
its eaither a bad song somewhere or something went wrong. i had a similar problem and it wouldnt install. i ran the file undoit.bat in dist and that forces uninstall and base reinstall. after that try again or there is an uninstall button in the song installer software that might help. hope this helps

**Comment by SoonerDoc** [comment]
Will give it a try. Thanks!!!

**Comment by bostongreekgeek** [comment]
the 0.5 mod has an undo and restore. That has worked for me several times when I though I was doing wrong and repeating thie procedure over and over and beat saber didnt work...restore.it worked...mess it up again :P But latest beat saber doesnt work with 0.5...so waiting for update

**Comment by NyanBlade** [comment]
Black screen issue should be mostly fixed in 0.6 https://github.com/NyanBlade/BeatSaberQuestInstaller/releases

Open an new issue if the problem still persists
