### ISSUE TITLE
Last version apk?

### ISSUE THREAD

**Issue by OversizedWizard** [NyanBlade/BeatSaberQuestInstaller#26]
Updated to latest version and list the custom songs.

Anyone have the apk installer for the previous versions?

**Comment by link2231** [comment]
not sure if running the uninstall and reinstall downgrades it but might be worth a try if you really want to get custom songs back

**Comment by OversizedWizard** [comment]
I've uninstalled and reinstalled but now I don't even have a custom songs tab.

Anyone done a backup apk of their working ver1.0.1

**Comment by jmscreation** [comment]
I've just tried it. The new Beat Saber update does not work!
I couldn't download the APK until I updated the game. It seems they made a patch that prevents custom song modding for the Quest.

**Comment by OversizedWizard** [comment]
I've found my original backup version 1.0.0.

I've installed that and modded again. All good again now

Least I can still play until the modders sort the new mod

**Comment by Adblue** [comment]
> I've found my original backup version 1.0.0.
> 
> I've installed that and modded again. All good again now
> 
> Least I can still play until the modders sort the new mod

How might I go about getting a backup of the last version?

**Comment by z7y8hsBP** [comment]
Did anyone try using custom songs with the current version of QuestStopgap from @emulamer?
According to the release notes it SHOULD be working, but I'm hesitating to update myself ;-)

**Comment by bostongreekgeek** [comment]
@handsomedude can you share the old apk for beat saber so we can do that to till the mod is fixed? Also, how do you sideload apks into the quest? is it similar to an android phone with adb via terminal commands?

**Comment by OversizedWizard** [comment]
Hi.  Use sidequest for a moment. It's works with latest version.

Modded with custom songs using sidequest and they appear in extra songs tab

**Comment by bostongreekgeek** [comment]
@handsomedude where do you get the base apk?

**Comment by bostongreekgeek** [comment]
@handsomedude never mind.. I [jfgi](http://bfy.tw/2jp) [sidequest](http://bfy.tw/O0Y4) and found out. Thank you.

**Comment by NyanBlade** [comment]
0.6 now supports 1.0.2
https://github.com/NyanBlade/BeatSaberQuestInstaller/releases
