### ISSUE TITLE
Version of [java.exe|songe-converter.exe|jarsigner.exe] is not compatible

### ISSUE THREAD

**Issue by telwell** [NyanBlade/BeatSaberQuestInstaller#27]
When running the installer on Windows 10 (1809 Oct 2018) I get the following error with the filenames above:
```
This version of _____ is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```

Thoughts on how to resolve?

**Comment by telwell** [comment]
bump

**Comment by NyanBlade** [comment]
> bump

Java is no longer required in 0.6 and it supports the latest version of Beat Saber (currently 1.0.2) so i'd suggest trying 0.6

**Comment by telwell** [comment]
Newest version didn't fix the issue unfortunately: https://imgur.com/a/PggZnvt
