### ISSUE TITLE
Doesnt work with newest BeatSaber from 06.06.19

### ISSUE THREAD

**Issue by DOC1973** [NyanBlade/BeatSaberQuestInstaller#28]
Hi,
very nice work and I honor it. For last update from BeatSaber it works fine but now from new update doesnt work Tool. If I integrate custom songs that game Beatsaber doesnt start and I have black Screen in Oculus Quest. I hope you have a fix in next time.

Best regards

**Comment by bostongreekgeek** [comment]
it is a known issue that NyanBlade is working one

**Comment by NyanBlade** [comment]
Download 0.6 for 1.0.2 support
