### ISSUE TITLE
Window is too small and cut off in v0.6

### ISSUE THREAD

**Issue by TheFreal** [NyanBlade/BeatSaberQuestInstaller#29]
![image](https://user-images.githubusercontent.com/8983392/59134394-4a2da980-897b-11e9-86a9-56d5a6db7f49.png)

This is under Windows 10, with a fresh install of the latest v0.6. The window is full-size in v0.5 as it should be, can't be resized, and a reboot doesn't change this behavior.

**Comment by NyanBlade** [comment]
> ![image](https://user-images.githubusercontent.com/8983392/59134394-4a2da980-897b-11e9-86a9-56d5a6db7f49.png)
> 
> This is under Windows 10, with a fresh install of the latest v0.6. The window is full-size in v0.5 as it should be, can't be resized, and a reboot doesn't change this behavior.

Hey, I reuploaded the 0.6 build to fix this issue. I used a 4K monitor this time and it messed up the resolution. Redownload 0.6 to fix it 👍

**Comment by TheFreal** [comment]
Redownloaded the latest commit, works beautifully now! Cheers!
