### ISSUE TITLE
BMBF launcher hangs during loading

### ISSUE THREAD

**Issue by g4rr3t** [NyanBlade/BeatSaberQuestInstaller#49]
Just setup my new Quest today, bought Beat Saber, loaded BMBF, uninstalled and reinstalled BS through BMBF.  However BMBF hangs on load and Beat Saber is unmodded.  From what I can figure out, I have the latest version of Beat Saber which is incompatible with BMBF.

**Comment by NyanBlade** [comment]
Now updated - https://github.com/NyanBlade/BeatSaberQuestInstaller/releases/tag/v1.2
