### ISSUE TITLE
Infinite loading on Oculus Quest

### ISSUE THREAD

**Issue by khuranadhruv18** [NyanBlade/BeatSaberQuestInstaller#52]
Whenever I press play on modded beat saber on the oculus quest, I receive an infinite loading screen with three dots and am not allowed to really start the game, even though I can click to start it. Does it just take a long time to load? I followed all the directions properly to the best of my knowledge. The only cause I can think for this is that the newest update of beat saber has patched modded beat saber probably?

**Comment by g4rr3t** [comment]
Your issue has been solved in previous reported issues.  Please check
previous issues before reporting a new one.  Enable storage permissions.
Library - Beat Saber Options - Permissions.

**Comment by JiveOff** [comment]
Did this help anyone?

**Comment by gorfreed** [comment]
Not true. The OP might experience the same infinite loading issue a certain percentage of BMBF users are experiencing. No matter which release, none of the devs have been able to troubleshoot why it is not working for them. A lot more detail here: https://github.com/kihecido/BMBF/issues/5
