### ISSUE TITLE
Stuck in "Performing Streamed Install" - administrator privileges needed?

### ISSUE THREAD

**Issue by mnylen** [NyanBlade/BeatSaberQuestInstaller#8]
First of all, thank you (and others) for making this possible. The vanilla Beat Saber is just... dull and this makes the experience so much better!

I tried using this just now and the first time I tried, the command prompt window of Step 6 got stuck with the message "Performing Streamed Install". I waited for an hour for it to complete, but nothing seemed to be happening, so I hit Ctrl-C to terminate + answering Y(es) to the confirmation.

After this, I went inside the Oculus Quest and I found Beat Saber was uninstalled from the device. I installed it back again from the Oculus Store and opened it. No custom songs were installed.

Next, I opened the QuestSongsInstaller.exe again, but this time I chose "run as administrator". Skipped right to Step 6, hit Install and it was able to complete in the matter of seconds.

Going inside Oculus Quest, Beat Saber was installed. This time around with all the custom songs I had downloaded 👍 

Just wondering if running as an administrator is a required step?

I remember seeing some log messages first time (when running as regular user) about not being able to write to some folder (was it AppData?). Those messages didn't reappear when running as admin though.

**Comment by MoltenHydrogen** [comment]
I think you just were unlucky the first time. The same happened to me, and it worked the second time without running as admin.

**Comment by truefriend-cz** [comment]
When will the error be fixed ???!!!

**Comment by MoltenHydrogen** [comment]
well, at this point you should just use sidequest
